### ISSUE TITLE
ValueError: Graph has cycles

### ISSUE THREAD

**Issue by FrozenGene** [tf-coreml/tf-coreml#189] opened 2018-05-28 05:48 UTC
When I convert tensorflow to CoreML, raise error: Graph has cycles. Model is here: https://github.com/mariolew/Deep-Alignment-Network-tensorflow

Sample Freezen Tensorflow model text file: 
[protobuf.txt.zip](https://github.com/tf-coreml/tf-coreml/files/2043746/protobuf.txt.zip)

Any workaround I can do? For example transform-tools? Thanks.

**Comment by aseemw** [comment] 2018-05-28 22:10
See issue #124 and example "ssd_example.ipynb" in which there are cycles in the beginning and end of graph, but after stripping the middle portion, it can be converted. Visualizing using netron or [tensorboard](https://github.com/tf-coreml/tf-coreml/blob/master/utils/visualize_pb.py) will help you find the cycle free graph(s).

**Comment by aseemw** [comment] 2018-06-09 17:22
Duplicate of #124

**Comment by Mstronach** [comment] 2019-10-16 22:26
This issue is being closed due to inactivity preceeding the request for an update. Please feel free to re-open if you are still seeing the issue. Thanks!

**Closed by Mstronach** 2019-10-16 22:26 UTC
Labels: duplicate
