### ISSUE TITLE
Can't convert re-trained InceptionV3 to coreml 

### ISSUE THREAD

**Issue by michaeldong** [tf-coreml/tf-coreml#110] opened 2018-01-18 10:35 UTC
`File "convert_temp.py", line 7, in 
input_name_shape_dict = {'input:0' : [1, 299, 299, 3]})
tfcoreml/_tf_coreml_converter.py", line 478, in convert
predicted_probabilities_output=predicted_probabilities_output)

/tfcoreml/_tf_coreml_converter.py", line 143, in _convert_pb_to_mlmodel
_check_unsupported_ops(OPS, output_feature_names)
tfcoreml/_tf_coreml_converter.py", line 111, in _check_unsupported_ops

','.join(unsupported_op_types)))
NotImplementedError: Unsupported Ops of type: DecodeJpeg,ResizeBilinear,PlaceholderWithDefault`
Anyone meet this issue?

**Comment by michaeldong** [comment] 2018-01-18 10:54
Oh, I update tfcoreml and reinsall it , NOW it only tips : Unsupported Ops of type: DecodeJpeg ,

how can i  ignore or solve it , Thank you for your reply!

**Comment by aseemw** [comment] 2018-01-18 23:14
Kindly look at the notebook: "examples/inception_v3.ipynb". That shows how to strip pre-processing nodes from the TF graph to prepare it for CoreML conversion.

**Comment by michaeldong** [comment] 2018-01-19 07:19
@aseemw Thanks for your immediately reply!

 I look at Your instruction  , by execute the script carefully.
I come across another problem.  change Input,output layer name to mine. 

AssertionError: input:0 is a placehoder with incomplete shape <unknown>
input is my layer name.

**Comment by michaeldong** [comment] 2018-01-19 07:32
This's code:  I can't not find out.
`# Save it to an output file
frozen_model_file = './flower_inception_v3.pb'
with gfile.GFile(frozen_model_file, "wb") as f:
    f.write(gdef.SerializeToString())


# Now we have a TF model ready to be converted to CoreML
import tfcoreml
# Supply a dictionary of input tensors' name and shape (with 
# batch axis)
input_tensor_shapes = {"input:0":[1,299,299,3]} # batch size is 1
# Output CoreML model path
coreml_model_file = './inception_v3.mlmodel'
# The TF model's ouput tensor name
output_tensor_names = ['softmax:0']

# Call the converter. This may take a while
coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names,
        image_input_names = ['input'],
        red_bias = -1,
        green_bias = -1,
        blue_bias = -1,
        image_scale = 2.0/255.0)`

**Comment by michaeldong** [comment] 2018-01-19 07:36
I change my code to this:
`frozen_model_file = './flower_inception_v3.pb'
with gfile.GFile(frozen_model_file, "wb") as f:
    f.write(gdef.SerializeToString())


import tfcoreml

input_tensor_shapes = {"input:0":[1,299,299,3]} # batch size is 1

coreml_model_file = './inception_v3.mlmodel'

output_tensor_names = ['softmax:0']


coreml_model = tfcoreml.convert(
        tf_model_path=frozen_model_file,
        mlmodel_path=coreml_model_file,
        input_name_shape_dict=input_tensor_shapes,
        output_feature_names=output_tensor_names,
        image_input_names = ['input'],
        red_bias = -1,
        green_bias = -1,
        blue_bias = -1,
        image_scale = 2.0/255.0)`

I Meet this issue.  Hope your reply. Thank you!

Caused by op u'InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D', defined at:
  File "convert.py", line 65, in <module>
    image_scale = 2.0/255.0)
  File "/home/youpinserver/xingdongdong/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 477, in convert
    predicted_probabilities_output=predicted_probabilities_output)
  File "/home/youpinserver/xingdongdong/tf-coreml/tfcoreml/_tf_coreml_converter.py", line 138, in _convert_pb_to_mlmodel
    tf.import_graph_def(gdef, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_0_0, InceptionV3/Conv2d_1a_3x3/weights). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_0_0, InceptionV3/Conv2d_1a_3x3/weights)]]

**Comment by aseemw** [comment] 2018-01-19 19:18
By looking at the error trace you post, "Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary", it seems that the issue is not in the converter stage. 
Forget about converting the model to CoreML for the moment, can you verify that the frozen .pb TF model  that you have works by itself? That is, can you load it and make a successful prediction with that model?

**Comment by aseemw** [comment] 2018-03-16 16:51
Closing now. Can be opened when there is more information.

**Closed by aseemw** 2018-03-16 16:51 UTC
Labels: repro needed
