### ISSUE TITLE
Get 'Graph has cycle' error although it is not.

### ISSUE THREAD

**Issue by younatics** [tf-coreml/tf-coreml#215] opened 2018-07-02 10:19 UTC
Hello @aseemw , 

I printed graph using below code.

[RNN_graph.txt](https://github.com/tf-coreml/tf-coreml/files/2154768/RNN_graph.txt)
[CNN_graph.txt](https://github.com/tf-coreml/tf-coreml/files/2154769/CNN_graph.txt)

```python
def _create_graph(ops):
  n = len(ops)
  G = [[] for i in range(n)]
  op_name_to_index = dict()
  #First pass to assign op name to its index
  for i, op in enumerate(ops):
#     print(i)
#     print(op.name)

    op_name_to_index[op.name] = i
        

  #Second pass to construct the graph
  print('-----')
  for i, op in enumerate(ops):
    for inp in op.inputs:
        print(inp.op.name)
        G[op_name_to_index[inp.op.name]].append(i)

  return G
```

I found `bidirectional_dynamic_rnn` has same graph name in graph (e.g. `lstm/rnn/while/rnn/layer_norm_basic_lstm_cell/split`)

I can't find solution for 7days although we can use `rnn`or `lstm` using `tf-coreml`. (https://github.com/tf-coreml/tf-coreml/issues/124)

---
RNN CODE
```python
    # model
    tf.reset_default_graph()

    global_step = tf.Variable(0, trainable=False, name='global_step')
    X = tf.placeholder(tf.float32, shape=[None, max_time, feature_count], name='Input')
    Y = tf.placeholder(tf.float32, shape=[None, output_count], name='Output')
    seq_len = tf.placeholder(tf.int32, shape=[None], name='seq_len')
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')

    # layers
    with tf.name_scope("forward"):
        lstm_fw_cell = tf.contrib.rnn.LayerNormBasicLSTMCell(lstm_units, forget_bias=1.0)
        lstm_fw_cell = tf.contrib.rnn.DropoutWrapper(lstm_fw_cell, output_keep_prob = 0.5)

    with tf.variable_scope("backward"):
        lstm_bw_cell = tf.contrib.rnn.LayerNormBasicLSTMCell(lstm_units, forget_bias=1.0)
        lstm_bw_cell = tf.contrib.rnn.DropoutWrapper(lstm_bw_cell, output_keep_prob = 0.5)

    with tf.name_scope('weights'):
        W = tf.get_variable(name="W", shape=[2 * lstm_units * max_time, output_count],
                        dtype=tf.float32, initializer = tf.contrib.layers.xavier_initializer())
        b = tf.get_variable(name="b", shape=[output_count], dtype=tf.float32,
                        initializer = tf.zeros_initializer())

    with tf.name_scope('bidirectional-lstm'):
        (output_fw, output_bw), states = tf.nn.bidirectional_dynamic_rnn(lstm_fw_cell, lstm_bw_cell, dtype=tf.float32, inputs = X, sequence_length = seq_len)
        outputs = tf.concat([output_fw, output_bw], axis=2)
        outputs_flat = tf.reshape(outputs, [-1, 2 * lstm_units * max_time])
        model = tf.matmul(outputs_flat, W) + b
        prediction = tf.argmax(model, 1, name='Prediction')
    
    with tf.name_scope('output'):
        model =  tf.matmul(outputs_flat, W) + b
        prediction = tf.argmax(outputs_flat, 1, name='Prediction')
        
    # optimizer
    with tf.name_scope('optimizer'):
        cost = tf.reduce_mean(
            tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=model)
        )
        optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
        train_op = optimizer.minimize(cost, global_step=global_step)
        tf.summary.scalar('cost', cost)
```

---
CNN code
```python

    def _build_weight(shape):
        global W, b
        
        W = tf.get_variable(name="W", shape=[shape[0], shape[1]],
                            dtype=tf.float32, initializer = tf.contrib.layers.xavier_initializer())
        b = tf.get_variable(name="b", shape=[shape[1]], dtype=tf.float32,
                            initializer = tf.zeros_initializer())
    def _build_output_layer():
        global model, logit, prediction

        model = tf.matmul(outputs_flat, W) + b
        logit = tf.nn.softmax(model, dim=1)
        prediction = tf.argmax(model, 1, name='Prediction')
    def _build_optimizer_layer():
        global cost, optimizer, train_op

        cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=model))
        optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
        train_op = optimizer.minimize(cost, global_step=global_step)
        tf.summary.scalar('cost', cost)

    def _build_accuracy_layer():
        global target, is_correct, accuracy

        target = tf.argmax(Y, 1)
        is_correct = tf.equal(prediction, target)
        accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))


    # model
    tf.reset_default_graph()
    
    global_step = tf.Variable(0, trainable=False, name='global_step')
    X = tf.placeholder(tf.float32, shape=[None, max_time, feature_count], name='Input')
    Y = tf.placeholder(tf.float32, shape=[None, output_count], name='Output')
    seq_len = tf.placeholder(tf.int32, shape=[None], name='seq_len')
    keep_prob = tf.placeholder(tf.float32, shape=None, name='keep_prob')

    # layers
    X_shape = tf.reshape(X, [-1, max_time, feature_count, 1])
    with tf.name_scope('layer1'):
        W1 = tf.Variable(tf.random_normal([2, feature_count, 1, 32], stddev=0.01))
        L1 = tf.nn.conv2d(X_shape, W1, strides=[1, 1, 1, 1], padding='SAME') # [ ?, 10, 63, 32 ]
        L1 = tf.nn.relu(L1)
        L1 = tf.nn.max_pool(L1, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME') # [ ?, 5, 32, 32 ]

    with tf.name_scope('layer2'):
        W2 = tf.Variable(tf.random_normal([3, int(feature_count / 2)+1, 32, 64], stddev=0.01))
        L2 = tf.nn.conv2d(L1, W2, strides=[1, 1, 1, 1], padding='SAME') # [ ?, 5, 32, 64 ]
        L2 = tf.nn.relu(L2)
        L2 = tf.nn.max_pool(L2, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME') # [ ?, 3, 16, 64 ]

    with tf.name_scope('layer3'):
        W3 = tf.Variable(tf.random_normal([3 * (int(feature_count / 4)+1) * 64, 256], stddev=0.01))
        L3 = tf.reshape(L2, [-1, 3 * (int(feature_count / 4)+1) * 64])
        L3 = tf.matmul(L3, W3)
        L3 = tf.nn.relu(L3)
        L3 = tf.nn.dropout(L3, 1.0)

    outputs_flat = L3
    _build_weight([256, output_count])
    
    _build_output_layer()
    _build_optimizer_layer()
    _build_accuracy_layer()
```

Could you help me to find graph or any other solution for this issue? 
Thanks!

<img width="595" alt="e1 84 89 e1 85 b3 e1 84 8f e1 85 b3 e1 84 85 e1 85 b5 e1 86 ab e1 84 89 e1 85 a3 e1 86 ba 202018-06-29 20 e1 84 8b e1 85 a9 e1 84 8c e1 85 a5 e1 86 ab 2011 27 27" src="https://user-images.githubusercontent.com/6335975/42159085-8337b89c-7e2d-11e8-9488-3e3c81ec7b0e.PNG">

<img width="909" alt="2018-07-02 7 24 03" src="https://user-images.githubusercontent.com/6335975/42159093-8a2817f0-7e2d-11e8-9857-f53363e1dcbd.png">

**Comment by aseemw** [comment] 2018-07-09 17:52
Duplicate of #124 
Inside RNN Cells there are cycles.

**Comment by Mstronach** [comment] 2019-10-23 21:54
This issue is being closed due to inactivity preceeding the request for an update. Please feel free to re-open if you are still seeing the issue. Thanks!

**Closed by Mstronach** 2019-10-23 21:54 UTC
Labels: duplicate
