### ISSUE TITLE
Issue in converting .pb model to .mlmodel

### ISSUE THREAD

**Issue by Saiktdey395** [tf-coreml/tf-coreml#190] opened 2018-05-30 10:56 UTC
Hi, I am facing an issue  **ModuleNotFoundError: No module named 'tfcoreml'** when I run these commands in a python file or in Terminal-

I have followed all the steps mentioned in https://github.com/tf-coreml/tf-coreml/blob/master/README.md

I used these commands to do the conversion-

**import tfcoreml as tf_converter
tf_converter.convert(tf_model_path = '/Users/new_mac/Desktop/PBtoCoreML/tensorflow_inception_graph.pb',
mlmodel_path = '/Users/new_mac/Desktop/PBtoCoreML/tensorflow_inception_graph.mlmodel',
output_feature_names = ['softmax:0'])**

I get a "No module named 'tfcoreml" error in my Terminal. 

Please advise where am I going wrong? Also let me know how to run these commands in terminal as I am new to Python.

**Comment by evanb2** [comment] 2018-05-30 19:41
How did you install `tf-coreml`?

**Comment by Saiktdey395** [comment] 2018-05-31 10:04
Hi @evanb2  I used this command **pip install -U tfcoreml** in my Terminal to install tf-coreml.

**Comment by aseemw** [comment] 2018-06-09 17:21
Duplicate of #172

**Comment by nirmalchoudhari** [comment] 2019-02-04 06:06
Do we have any resolution for this?

**Comment by Mstronach** [comment] 2019-10-16 22:27
Please try this installation: https://github.com/tf-coreml/tf-coreml/blob/master/README.md#new-fire-tfcoreml-converter-with-core-ml-3 and re-open this issue if you are still having issues. Thanks!

**Closed by Mstronach** 2019-10-16 22:27 UTC
Labels: duplicate
